-- CreateTable
CREATE TABLE `speed_tests` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NULL,
    `cpf` VARCHAR(191) NULL,
    `downloadMbps` DOUBLE NULL,
    `uploadMbps` DOUBLE NULL,
    `pingMs` DOUBLE NULL,
    `jitterMs` DOUBLE NULL,
    `packetLoss` DOUBLE NULL,
    `downloadBytes` DOUBLE NULL,
    `downloadDurationMs` INTEGER NULL,
    `downloadConnections` INTEGER NULL,
    `uploadBytes` DOUBLE NULL,
    `uploadDurationMs` INTEGER NULL,
    `uploadConnections` INTEGER NULL,
    `pingSamplesCount` INTEGER NULL,
    `pingSamples` JSON NULL,
    `appVersion` VARCHAR(191) NULL,
    `platform` VARCHAR(191) NULL,
    `osVersion` VARCHAR(191) NULL,
    `deviceModel` VARCHAR(191) NULL,
    `connectionType` VARCHAR(191) NULL,
    `carrier` VARCHAR(191) NULL,
    `clientIp` VARCHAR(191) NULL,
    `userAgent` TEXT NULL,
    `serverHost` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'completed',
    `errorMessage` TEXT NULL,
    `config` JSON NULL,
    `raw` JSON NULL,
    `startedAt` DATETIME(3) NULL,
    `finishedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `speed_tests_cpf_idx`(`cpf`),
    INDEX `speed_tests_userId_idx`(`userId`),
    INDEX `speed_tests_createdAt_idx`(`createdAt`),
    INDEX `speed_tests_cpf_createdAt_idx`(`cpf`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
