services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: predialnet
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8080:8080"

  mysql-backup:
    image: debian:latest
    container_name: mysql-backup
    depends_on:
      - mysql
    volumes:
      - mysql-data:/var/lib/mysql:ro
      - ./backups:/backup
    tty: true
    stdin_open: true
    entrypoint: >
      bash -c "
        apt-get update &&
        apt-get install -y cron mariadb-client &&
        echo '0 3 * * * root mysqldump -h mysql -uadmin -padmin predialnet > /backup/db-$(date +\%F).sql' > /etc/cron.d/mysql-backup &&
        chmod 0644 /etc/cron.d/mysql-backup &&
        crontab /etc/cron.d/mysql-backup &&
        cron -f
      "

volumes:
  mysql-data:
