services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: predialnet
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8080:8080"

volumes:
  mysql-data:
