services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: app_predialnet_db
    restart: always
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
